name: DamselflyBuild
on: 
  push:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)    
        required: false

jobs:
  build-desktop:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix: 
        target: [universal, linux, windows]
        include: 
          - target: windows
            os: windows-latest
            upload: windows
          - target: linux
            os: ubuntu-latest
            upload: linux
          - target: universal
            os: macos-latest
            upload: mac

    steps:
      - name: Clone Repository (latest)
        uses: actions/checkout@v3
        if: github.event.inputs.git-ref == ''

      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v3
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Run Electron build
        run: sh scripts/makedesktop.sh ${{ matrix.target }}

      - name: Upload desktop builds for Docker build
        uses: actions/upload-artifact@v4
        with:
          name: Desktop-Dist-${{ matrix.upload }}
          path: Damselfly.Web.Client/wwwroot/desktop/*.*
          retention-days: 5

  build-server:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix: 
        target: [linux, mac, windows]
        include: 
          - target: windows
            os: ubuntu-latest
          - target: linux
            os: ubuntu-latest
          - target: mac
            os: macos-latest

    steps:
      - name: Clone Repository (latest)
        uses: actions/checkout@v5
        if: github.event.inputs.git-ref == ''

      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v5
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}

      - name: Setup Dotnet Environment
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.100
      
      - name: Install WASM-Tools
        run: dotnet workload install wasm-tools

      - name: Run Dotnet Server Build
        run: sh scripts/makeserver.sh ${{ matrix.target }} 

      - name: Upload server builds to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Server-Dist-${{ matrix.target }}
          path: server/*.zip     
          retention-days: 5

  build-docker:
    needs: [build-server, build-desktop]
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix: 
        target: [linux]
        include: 
          - target: linux
            os: ubuntu-latest
    steps:        
      - name: Clone Repository (latest)
        uses: actions/checkout@v3
        if: github.event.inputs.git-ref == ''

      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v3
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}

      - name: Read VERSION file
        id: getversion
        run: echo "::set-output name=version::$(cat VERSION)"

      - name: Download Server Build
        uses: actions/download-artifact@v4
        with:
          name: Server-Dist-${{ matrix.target }}
          path: server

      - name: Unzip server into publish folder
        run: |
             mkdir publish
             cd publish
             unzip $GITHUB_WORKSPACE/server/damselfly-server-${{ matrix.target }}-*.zip
             cd ..

      - name: Validate Server artifacts
        run: |
             echo "Server artifacts:"
             ls server

      - name: Download Mac Desktop Builds into wwwroot folder
        uses: actions/download-artifact@v4
        with:
          name: Desktop-Dist-mac
          path: publish/wwwroot/desktop

      - name: Download Windows Desktop Builds into wwwroot folder
        uses: actions/download-artifact@v4
        with:
          name: Desktop-Dist-windows
          path: publish/wwwroot/desktop
      
      - name: Download Linux Desktop Builds into wwwroot folder
        uses: actions/download-artifact@v4
        with:
          name: Desktop-Dist-linux
          path: publish/wwwroot/desktop

      - name: Validate Desktop artifacts
        run: |
             echo "Desktop artifacts:"
             ls publish/wwwroot/desktop
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build Docker for Dev (develop only)
        if: github.ref == 'refs/heads/develop'
        run: sh scripts/makedocker.sh

      - name: Build Docker for Release (master only)
        if: github.ref == 'refs/heads/master'
        run: sh scripts/makedocker.sh master

      - name: Create Release (master only)
        id: create_release
        if: github.ref == 'refs/heads/master'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ steps.getversion.outputs.version }}
          release_name: Release v${{ steps.getversion.outputs.version }}
          body: |
            Docker: docker pull webreaper/damselfly:${{ steps.getversion.outputs.version }}
          draft: false
          prerelease: false

      - name: Download Linux Desktop Artifacts
        if: github.ref == 'refs/heads/master'
        uses: actions/download-artifact@v4
        with:
          name: Desktop-Dist-linux
          path: Damselfly.Web.Client/wwwroot/desktop

      - name: Download Mac Desktop Artifacts
        if: github.ref == 'refs/heads/master'
        uses: actions/download-artifact@v4
        with:
          name: Desktop-Dist-mac
          path: Damselfly.Web.Client/wwwroot/desktop
          
      - name: Download Windows Desktop Artifacts
        if: github.ref == 'refs/heads/master'
        uses: actions/download-artifact@v4
        with:
          name: Desktop-Dist-windows
          path: Damselfly.Web.Client/wwwroot/desktop

      - name: Download Server Artifacts
        if: github.ref == 'refs/heads/master'
        uses: actions/download-artifact@v4
        with:
          name: Server-Dist
          path: server

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release v${{ steps.getversion.outputs.version }}
          tag_name: ${{ steps.getversion.outputs.version }}
          make_latest: true
          body: |
            Docker: docker pull webreaper/damselfly:${{ steps.getversion.outputs.version }}
          files: |
            server/Server-Dist-linux.zip
            Damselfly.Web.Client/wwwroot/desktop/Desktop-Dist-linux.zip
            server/Server-Dist-max.zip
            Damselfly.Web.Client/wwwroot/desktop/Desktop-Dist-mac.zip
            server/Server-Dist-windows.zip
            Damselfly.Web.Client/wwwroot/desktop/Desktop-Dist-windows.zip
    
